[package]
name = "crabflow"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "crabflow_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
directories = "5.0"
dirs = "5"
tauri = { version = "2.0.0-beta.21", features = [] }
tauri-plugin-opener = "2.0.0-beta.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.10.0", features = ["v4"] }
sysinfo = "0.30"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
is_elevated = "0.1"
axum = { version = "0.7.5", features = ["macros"] }
tokio = { version = "1.39.2", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
get_if_addrs = "0.5.3"
surrealdb = { version = "2.0.0-beta.8", features = ["kv-surrealkv"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
base64 = "0.22"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
